version: '2'
services:
    eventsearch-app:
        image: eventsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://eventsearch-postgresql:5432/eventsearch
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=eventsearch-elasticsearch:9300
        ports:
            - 8080:8080
    eventsearch-postgresql:
        extends:
            file: postgresql.yml
            service: eventsearch-postgresql
    eventsearch-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: eventsearch-elasticsearch
